tap 'caskroom/cask'
  brew 'bat'
  brew 'fzf'
  brew 'git'
  brew 'htop'
  brew 'n'
  brew 'neovim'
  brew 'sqlite'
  brew 'wget'
  brew 'yarn'

  cask 'brave-browser'
  cask 'postman'
  cask 'spotify'
  cask 'visual-studio-code'
